In [1]:
%load_ext sql

In [2]:
%sql ibm_db_sa://trc19485:53kfgv1n1%2Br49sth@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB

DB2/LINUXX8664

In [3]:
%sql select * from SYSCAT.COLUMNS where TABNAME= 'CHICAGO_CRIME_DATA'

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('TRC19485', 'CHICAGO_CRIME_DATA', 'ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 533, '11233321', '23469', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'CASE_NUMBER', 1, 'SYSIBM  ', 'VARCHAR', 8, 0, 'OCTETS', 8, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 533, "'JB155558'", "'G040244'", 13, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 8, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'DATE', 2, 'SYSIBM  ', 'DATE', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 504, "'2018-02-16'", "'2001-01-19'", 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'BLOCK', 3, 'SYSIBM  ', 'VARCHAR', 35, 0, 'OCTETS', 35, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 533, "'132XX S RIVERDALE AVE'", "'0000X E OHIO ST'", 23, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 18, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'IUCR', 4, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 112, "'930'", "'041A'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'PRIMARY_TYPE', 5, 'SYSIBM  ', 'VARCHAR', 33, 0, 'OCTETS', 33, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 35, "'THEFT'", "'ASSAULT'", 15, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 10, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'DESCRIPTION', 6, 'SYSIBM  ', 'VARCHAR', 46, 0, 'OCTETS', 46, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 103, "'VEHICULAR HIJACKING'", "'AGG CRIM SEX ABUSE FAM MEMBER'", 21, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 16, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'LOCATION_DESCRIPTION', 7, 'SYSIBM  ', 'VARCHAR', 33, 0, 'OCTETS', 33, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 48, "'VEHICLE NON-COMMERCIAL'", "'ALLEY'", 16, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 11, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'ARREST', 8, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "'TRUE'", "'FALSE'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'DOMESTIC', 9, 'SYSIBM  ', 'VARCHAR', 5, 0, 'OCTETS', 5, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "'TRUE'", "'FALSE'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'BEAT', 10, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 242, '2534', '112', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'DISTRICT', 11, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 22, '24', '2', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'WARD', 12, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 51, '50', '2', 3, None, 0, 20, 10, 43, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'COMMUNITY_AREA_NUMBER', 13, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 71, '77', '2', 3, None, 0, 20, 10, 43, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'FBICODE', 14, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 23, "'7'", "'04A'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'X_COORDINATE', 15, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 505, '1204126', '1100955', 5, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'Y_COORDINATE', 16, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 469, '1951001', '1817235', 5, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'YEAR', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 18, '2017', '2002', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'LATITUDE', 18, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', 497, '+0000000042.02117760', '+0000000041.65371054', 11, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'LONGITUDE', 19, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', 489, '-0000000087.52822298', '-0000000087.90412276', 11, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_CRIME_DATA', 'LOCATION', 20, 'SYSIBM  ', 'VARCHAR', 29, 0, 'OCTETS', 29, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 505, "'(42.021177601, -87.67220843)'", "'(41.653710537, -87.609528714)'", 34, None, 0, 20, 10, 4, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 29, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

In [10]:
# Problem 1 total number of crimes in the CHICAGO CRIME DATA table
%sql select count(CASE_NUMBER) from CHICAGO_CRIME_DATA \
where PRIMARY_TYPE not in ('NON - CRIMINAL', 'NON-CRIMINAL', 'NON-CRIMINAL (SUBJECT SPECIFIED)')
# I excluded all non-criminal cases from the count through the 'where ... not in()' command

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('530'),)]

In [4]:
%sql select * from SYSCAT.COLUMNS where TABNAME='CENSUS_DATA'

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('TRC19485', 'CENSUS_DATA', 'COMMUNITY_AREA_NUMBER', 0, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '77', '2', 3, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CENSUS_DATA', 'COMMUNITY_AREA_NAME', 1, 'SYSIBM  ', 'VARCHAR', 22, 0, 'OCTETS', 22, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 78, "'West Town'", "'Archer Heights'", 16, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 11, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CENSUS_DATA', 'PERCENT_OF_HOUSING_CROWDED', 2, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 56, '+015.2', '+000.8', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CENSUS_DATA', 'PERCENT_HOUSEHOLDS_BELOW_POVERTY', 3, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 68, '+051.2', '+003.4', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CENSUS_DATA', 'PERCENT_AGED_16__UNEMPLOYED', 4, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 67, '+034.6', '+004.9', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CENSUS_DATA', 'PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA', 5, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 70, '+051.5', '+002.6', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CENSUS_DATA', 'PERCENT_AGED_UNDER_18_OR_OVER_64', 6, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 67, '+044.9', '+017.0', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CENSUS_DATA', 'PER_CAPITA_INCOME', 7, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '71551', '10402', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CENSUS_DATA', 'HARDSHIP_INDEX', 8, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '98', '2', 3, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

In [18]:
# Problem 2 List of community areas with per capita income less than 11000
%sql select COMMUNITY_AREA_NAME, PER_CAPITA_INCOME from CENSUS_DATA where PER_CAPITA_INCOME <11000

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('West Garfield Park', 10934),
 ('South Lawndale', 10402),
 ('Fuller Park', 10432),
 ('Riverdale', 8201)]

In [11]:
# problem 3 all case numbers for crimes involving minors
%sql select CASE_NUMBER, DESCRIPTION from CHICAGO_CRIME_DATA where IUCR \
in ('2210', '2220', '2230', '2240', '2251', '2070', '1840', '1792', '1791', '1790', '1780', '1775',\
    '1755', '1754', '1753', '1752', '1751', '1750', '1725', '1720', '1715', '1710', '1582', '1565',\
    '1544', '1541', '1531', '1526', '1521', '485')
# I looked up all IUCR codes on the chicago police department site, where in the secondary description 'minor' or 'child' 
# was listed.
# for clarity purposes I included the description column in the resultlist.

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('HN567387', 'AGG SEX ASSLT OF CHILD FAM MBR'),
 ('HR391350', 'SEX ASSLT OF CHILD BY FAM MBR'),
 ('HM768251', 'CRIM SEX ABUSE BY FAM MEMBER'),
 ('HT394616', 'AGG CRIM SEX ABUSE FAM MEMBER'),
 ('HL266884', 'SELL/GIVE/DEL LIQUOR TO MINOR'),
 ('HK238408', 'ILLEGAL CONSUMPTION BY MINOR'),
 ('HN144152', 'CHILD ABDUCTION/STRANGER')]

In [17]:
# problem 4 list of all kidnapping crimes involving a child
%sql select CASE_NUMBER from CHICAGO_CRIME_DATA where DESCRIPTION = 'CHILD ABDUCTION/STRANGER'

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('HN144152',)]

In [25]:
# problem 5 crime types recorded at schools
%sql select PRIMARY_TYPE, DESCRIPTION, LOCATION_DESCRIPTION from CHICAGO_CRIME_DATA where LOCATION_DESCRIPTION \
in ('SCHOOL, PRIVATE, BUILDING','SCHOOL, PUBLIC, BUILDING','SCHOOL, PUBLIC, GROUNDS')

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('BATTERY', 'SIMPLE', 'SCHOOL, PUBLIC, GROUNDS'),
 ('BATTERY', 'PRO EMP HANDS NO/MIN INJURY', 'SCHOOL, PUBLIC, BUILDING'),
 ('BATTERY', 'SIMPLE', 'SCHOOL, PUBLIC, BUILDING'),
 ('BATTERY', 'SIMPLE', 'SCHOOL, PUBLIC, BUILDING'),
 ('BATTERY', 'SIMPLE', 'SCHOOL, PUBLIC, GROUNDS'),
 ('CRIMINAL DAMAGE', 'TO VEHICLE', 'SCHOOL, PUBLIC, GROUNDS'),
 ('NARCOTICS', 'POSS: HEROIN(WHITE)', 'SCHOOL, PUBLIC, GROUNDS'),
 ('NARCOTICS', 'MANU/DEL:CANNABIS 10GM OR LESS', 'SCHOOL, PUBLIC, BUILDING'),
 ('ASSAULT', 'PRO EMP HANDS NO/MIN INJURY', 'SCHOOL, PUBLIC, GROUNDS'),
 ('CRIMINAL TRESPASS', 'TO LAND', 'SCHOOL, PUBLIC, GROUNDS'),
 ('PUBLIC PEACE VIOLATION', 'BOMB THREAT', 'SCHOOL, PRIVATE, BUILDING'),
 ('PUBLIC PEACE VIOLATION', 'BOMB THREAT', 'SCHOOL, PUBLIC, BUILDING')]

In [26]:
# problem 6a list of average safety score for all types of schools
%sql select avg(SAFETY_SCORE) as AVERAGE_SAFETY_SCORE from CHICAGO_PUBLIC_SCHOOLS

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('49.504873'),)]

In [7]:
%sql select * from SYSCAT.COLUMNS where TABNAME='CHICAGO_PUBLIC_SCHOOLS'

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'school_type', 2, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'MS'", "'ES'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Street_Address', 3, 'SYSIBM  ', 'VARCHAR', 29, 0, 'OCTETS', 29, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'9912 S Avenue H'", "'10015 S Leavitt St'", 22, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 17, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'City', 4, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'Chicago'", "'Chicago'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'State', 5, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'IL'", "'IL'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'ZIP_Code', 6, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 51, '60707', '60607', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Phone_Number', 7, 'SYSIBM  ', 'VARCHAR', 14, 0, 'OCTETS', 14, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'(773) 535-9930'", "'(773) 534-0146'", 19, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 14, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Link', 8, 'SYSIBM  ', 'VARCHAR', 78, 0, 'OCTETS', 78, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "''", "'http://schoolreports.cps.edu/Scho'", 83, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 78, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Network_Manager', 9, 'SYSIBM  ', 'VARCHAR', 40, 0, 'OCTETS', 40, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 20, "'Southwest Side High School Networ'", "'Austin-North Lawndale Elementary '", 35, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 30, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Collaborative_Name', 10, 'SYSIBM  ', 'VARCHAR', 34, 0, 'OCTETS', 34, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 5, "'SOUTHWEST SIDE COLLABORATIVE'", "'NORTH-NORTHWEST SIDE COLLABORATIV'", 33, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 28, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Adequate_Yearly_Progress_Made_', 11, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'Yes'", "'NDA'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Track_Schedule', 12, 'SYSIBM  ', 'VARCHAR', 12, 0, 'OCTETS', 12, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'Track_E'", "'Non_Standard'", 13, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 8, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'CPS_Performance_Policy_Status', 13, 'SYSIBM  ', 'VARCHAR', 16, 0, 'OCTETS', 16, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Not on Probation'", "'Not Applicable'", 18, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 13, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'CPS_Performance_Policy_Level', 14, 'SYSIBM  ', 'VARCHAR', 15, 0, 'OCTETS', 15, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 5, "'NDA'", "'Level 2'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'HEALTHY_SCHOOL_CERTIFIED', 15, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "'Yes'", "'No'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Safety_Icon', 16, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'SAFETY_SCORE', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 86, '99', '5', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Family_Involvement_Icon', 18, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Family_Involvement_Score', 19, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 72, "'99'", "'17'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Environment_Icon', 20, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Environment_Score', 21, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 80, '99', '2', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Instruction_Icon', 22, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Instruction_Score', 23, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 83, '99', '11', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Leaders_Icon', 24, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'Weak'", "'Weak'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'School_ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 566, '610543', '609674', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'NAME_OF_SCHOOL', 1, 'SYSIBM  ', 'VARCHAR', 65, 0, 'OCTETS', 65, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'Woodlawn Community Elementary Sch'", "'Abraham Lincoln Elementary School'", 41, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 36, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Leaders_Score', 25, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 79, "'99'", "'14'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Teachers_Icon', 26, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Teachers_Score', 27, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 77, "'99'", "'14'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Parent_Engagement_Icon', 28, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Strong'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Parent_Engagement_Score', 29, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 32, "'69'", "'39'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Parent_Environment_Icon', 30, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Strong'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Parent_Environment_Score', 31, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 33, "'70'", "'36'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'AVERAGE_STUDENT_ATTENDANCE', 32, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 155, "'98.40%'", "'60.90%'", 11, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Rate_of_Misconducts__per_100_students_', 33, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 288, '+0230.6', '+0000.1', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Average_Teacher_Attendance', 34, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 55, "'98.10%'", "'91.70%'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Individualized_Education_Program_Compliance_Rate', 35, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 69, "'99.60%'", "'72.70%'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Pk_2_Literacy__', 36, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 308, "'96.3'", "'16.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Pk_2_Math__', 37, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 224, "'97.2'", "'10.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr3_5_Grade_Level_Math__', 38, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 336, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr3_5_Grade_Level_Read__', 39, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 340, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr3_5_Keep_Pace_Read__', 40, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 276, "'82.5'", "'28.8'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr3_5_Keep_Pace_Math__', 41, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'83.5'", "'21.7'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr6_8_Grade_Level_Math__', 42, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 296, "'96.5'", "'10.2'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr6_8_Grade_Level_Read__', 43, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 300, "'98.9'", "'100'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr6_8_Keep_Pace_Math_', 44, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 268, "'93.6'", "'24.3'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr6_8_Keep_Pace_Read__', 45, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'85.5'", "'21.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr_8_Explore_Math__', 46, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 208, "'9.7'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'Gr_8_Explore_Read__', 47, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 244, "'99'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Exceeding_Math__', 48, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 297, '+0100.0', '+0000.6', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Exceeding_Reading__', 49, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 261, '+0100.0', '+0000.5', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Value_Add_Math', 50, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 57, '+03.6', '-03.1', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('TRC19485', 'CHICAGO_PUBLIC_SCHOOLS', 'ISAT_Value_Add_Read', 51, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 60, '+04.9', '-02.8', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),

In [12]:

%sql select SCHOOL_TYPE from CHICAGO_PUBLIC_SCHOOLS limit 5

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('ES',), ('ES',), ('ES',), ('ES',), ('HS',)]

In [14]:
#problem 6b average safety score per school type
%sql select SCHOOL_TYPE, avg(SAFETY_SCORE) as AVERAGE_SAFETY_SCORE from CHICAGO_PUBLIC_SCHOOLS group by SCHOOL_TYPE;
# I wasn't sure you wanted the overall average score, or the average score per school type. So I performed both queries.

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('ES', Decimal('49.520383')),
 ('HS', Decimal('49.623529')),
 ('MS', Decimal('48.000000'))]

In [18]:
# problem 7: 5 community areas with highest % of households below poverty line
%sql select COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY from CENSUS_DATA \
order by PERCENT_HOUSEHOLDS_BELOW_POVERTY desc fetch first 5 rows only

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Riverdale', Decimal('56.5')),
 ('Fuller Park', Decimal('51.2')),
 ('Englewood', Decimal('46.6')),
 ('North Lawndale', Decimal('43.1')),
 ('East Garfield Park', Decimal('42.4'))]

In [6]:
# problem 8 community area number with highest recorded crimerate (most prone to crime)
%sql select COMMUNITY_AREA_NUMBER, count(COMMUNITY_AREA_NUMBER) as CRIMENUMBER from CHICAGO_CRIME_DATA \
group by COMMUNITY_AREA_NUMBER order by count(COMMUNITY_AREA_NUMBER) desc limit 1

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(25, Decimal('43'))]

In [16]:
#problem 9 Name of community area with highest hardship index score
%sql select COMMUNITY_AREA_NAME from CENSUS_DATA where HARDSHIP_INDEX = (select max(HARDSHIP_INDEX) from CENSUS_DATA)

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Riverdale',)]

In [9]:
# problem 10 Name of community area most prone to crime
%sql select COMMUNITY_AREA_NAME, CD.COMMUNITY_AREA_NUMBER from CENSUS_DATA CD \
where CD.COMMUNITY_AREA_NUMBER in (select CR.COMMUNITY_AREA_NUMBER from CHICAGO_CRIME_DATA CR\
group by CR.COMMUNITY_AREA_NUMBER order by count(CR.COMMUNITY_AREA_NUMBER) desc limit 1)
#for control purposes I included the community area number in the list. The answer to the question is Austin

 * ibm_db_sa://trc19485:***@dashdb-txn-sbox-yp-lon02-13.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Austin', 25)]